#!/usr/bin/env perl
use strict;

sub above_average {
    my($sum, $avg, @result) = (0,0,());
    for(@_) {
        $sum += $_;
    }

    $avg = $sum / scalar(@_);
    for(@_) {
        if($_ > $avg) {
            push @result, $_;
        }
    }
    @result;
}



my @fred = above_average(1..10);
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";

my @barney = above_average(100, 1..10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";
