#!/usr/bin/env perl
use 5.014;

sub greet {
    my $greet_to = $_[0];
    state @people;

    if (!@people) {
        print "Hi $greet_to! You are the first one here!\n";
    } else {
        print "Hi $greet_to! I've seen: @people\n";
    }
    push @people, $greet_to;
}

greet( "Fred" );
greet( "Barney" );
greet( "Wilma" );
greet( "Betty" );
